version: '3.8'
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - "/Volumes/Crucial X9 Pro For Mac/teche:/root/.ollama"
    command: >
      sh -c "ollama serve & sleep 5 && ollama pull gpt-oss && tail -f /dev/null"

volumes:
  ollama-data: