# Prometheus configuration for Kaggle Multi-Agent System

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'kaggle-agents'
    environment: 'development'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

# Rules for alerting (optional)
# rule_files:
#   - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Docker metrics (requires cAdvisor or Docker metrics endpoint)
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    metrics_path: /metrics

  # Redis metrics (requires redis_exporter)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']

  # PostgreSQL metrics (requires postgres_exporter)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']

  # Application metrics (if you implement Prometheus endpoint in the app)
  # - job_name: 'kaggle-agent'
  #   static_configs:
  #     - targets: ['kaggle-agent:8000']
  #   metrics_path: /metrics

  # Node exporter for system metrics (optional)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']